# Generated by Django 3.1.1 on 2020-09-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0003_auto_20200911_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobform',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='jobform',
            name='city',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='jobform',
            name='country',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='jobform',
            name='pincode',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
