# Generated by Django 3.1.1 on 2020-09-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0004_auto_20200914_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobform',
            name='dob',
            field=models.DateField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='jobform',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F'), ('other', 'O')], default='GENDER', max_length=20),
        ),
    ]
